### PR TITLE
Please confirm ASAP

### PR DESCRIPTION
**Pull request by chi6rag**

### CODE REVIEW

**Comment by chi6rag** [comment]
[Sign Up](http://res.cloudinary.com/chi6rag/image/upload/v1432092220/HourGlass/sign_up.jpg)
sign_up

[User Check In](http://res.cloudinary.com/chi6rag/image/upload/v1432092220/HourGlass/user_check_in.jpg)
user_check_in

[User Check Out](http://res.cloudinary.com/chi6rag/image/upload/v1432092220/HourGlass/user_check_out.jpg)
user_check_out

[User Result](http://res.cloudinary.com/chi6rag/image/upload/v1432092220/HourGlass/user_result.jpg)
user_result

[User Report](http://res.cloudinary.com/chi6rag/image/upload/v1432092220/HourGlass/user_report.jpg)
User Report

[Admin Dash](http://res.cloudinary.com/chi6rag/image/upload/v1432092220/HourGlass/admin_dash.jpg)
admin_dash

[Admin's User Report](http://res.cloudinary.com/chi6rag/image/upload/v1432092221/HourGlass/admin_user_report.jpg)
admin_user_report

**Comment by bvsatyaram** [comment]
Hey Chirag! Did you handle the case where a user checks-in multiple times in a day?
Eg. A guy comes in the morning, leaves for lunch, comes back and then leaves.

**Comment by chi6rag** [comment]
Umm... It's just for the day as of now

**Comment by chi6rag** [comment]
As of now, the user cannot make multiple check ins in a day

**Pull request merged**
